config/routes.rb
Rails.application.routes.draw do
  get 'summary/index'
  get 'registered_business/index'
  resources :extra_employees
  resources :townships
  devise_for :users, controllers: {
    sessions: 'users/sessions'
             }


  resources :application_requests
  resources :workplaces
  get 'home/index'
  get 'users', to: "users#index"
  get 'users/new' => "users#new", as: :new_user



  get 'user/:id' => "users#show", as: :get_user
  post 'create_user' => "users#create", as: :create_user
  patch 'update_user/:id' => "users#update", as: :update_user
  get 'edit_user/:id' => "users#edit", as: :edit_user
  delete "destroy_user/:id" => "users#destroy", as: :destroy_user

  get "my_application_requests/:id/new_employees" => "application_requests#new_employees", as: :new_employees
  post "grid_data/batch_create_application_requests/:id", to: "application_requests#batch_create", as: "application_request_batch_create"

  get "my_application_requests/:id/grid" => "application_requests#employee_list", as: :employee_list
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post "grid_data/application_requests/:id", to: "application_requests#data_update", as: "application_requests_data_update"
  delete "grid_data/batch_delete_application_requests/:id", to: "application_requests#batch_delete", as: "application_request_batch_delete"

  post "change_state_application_request/:id", to: "application_requests#change_state", as: "application_request_change_state"
  post "change_state_workplace/:id", to: "workplaces#change_state", as: "workplace_change_state"
  get "public/new_form" => "public_workplaces#new", as: :new_public_form
  post "public/create_form" => "public_workplaces#create", as: :create_public_form
  get "public/success" => "public_workplaces#success", as: :success_form
  root "public_workplaces#index"



  get 'workplaces' => "workplaces#index", aasm_state: "pending", as: "workplaces_index"
  get 'summary/index'
  post 'summary/print'

  post "print_application_request" => "application_requests#print"

end

app/models/user.rb
class User < ApplicationRecord
  include Rails.application.routes.url_helpers
  include ActionView::Helpers::UrlHelper

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:masqueradable

  has_many :user_townships, dependent: :destroy
  has_many :townships, through: :user_townships


  has_many :workplaces, primary_key: "id", foreign_key: "owner_id", dependent: :destroy

  has_many :verfied_workplaces,class_name: "ApplicationRequest", primary_key: "id", foreign_key: "verify_by"
  has_many :rejected_workplaces,class_name: "ApplicationRequest", primary_key: "id", foreign_key: "reject_by"
  has_many :approved_workplaces,class_name: "ApplicationRequest", primary_key: "id", foreign_key: "approve_by"
  has_many :submitted_workplaces,class_name: "ApplicationRequest", primary_key: "id", foreign_key: "submit_by"

  def is_industry_user?
    if townships.present?
      townships.first.ts_pcode.include? "IND"
    else
      false
    end
  end

  def self.view_columns
    {
      name: { source: "User.name", cond: :like},
      organization_name: { source: "User.organization_name", cond: :like},
      email: { source: "User.email", cond: :like},
      user_role: { source: "User.user_role", cond: :like},
      title: { source: "User.title", cond: :like},
      township: { source: "User.ts_pcode", cond: :eq},
      actions: { source: "User.id", cond: :eq }

    }
  end

  def custom_attributes
    actions = ""
#    actions += link_to(I18n.t("reset_password"),"",class: "btn btn-link float-left")
    actions += link_to(I18n.t("view"),get_user_path(self),class: "btn btn-link float-left")
    actions += link_to(I18n.t("edit"),edit_user_path(self),class: "btn btn-link float-left")
    actions += link_to(I18n.t("delete"),destroy_user_path(self),method: :delete, class: "btn btn-link float-left")

    { township:  townships.pluck(:name).join(","), actions: actions.html_safe }
      #.merge({ actions: link_to("Login", Rails.application.routes.url_helpers.user_masquerade_path(self))})
  end

  def generate_application_requests
    if company?
      workplaces.map(&:create_application_request)
    end
  end




  def sys_admin?
    user_role == "SystemAdmin"
  end

  def admin?
    user_role == "Admin"
  end

  def company?
    user_role == "Company"
  end

  def accounting_manager?
    user_role == "AccountManager"
  end

  def account_manager?
    user_role == "AccountManager"
  end

  def verification_officer?
    user_role == "Verification Officer"
  end

  def approving_officer?
    user_role == "Approving Officer"
  end

  def readonly_admin?
    user_role == "Readonly Admin"
  end

  def printonly_admin?
    user_role == "Printonly Admin"
  end

  def my_managable_users
    if company?
      []
    elsif accounting_manager?
      User.where(id: my_workplaces.pluck(:owner_id))
    else
      User.all
    end
  end



  def my_managable_application_requests
    ApplicationRequest.joins(:workplace).merge(my_workplaces)
  end

  def my_workplaces
    if company?
      workplaces
    elsif accounting_manager?
      Workplace.where(ts_pcode: townships.pluck(:ts_pcode))
    elsif verification_officer?
      Workplace.where(ts_pcode: townships.pluck(:ts_pcode))
    elsif readonly_admin?
      Workplace.all
    else
      Workplace.all
    end
  end






  def my_creatable_roles
    case user_role
    when "SystemAdmin"
      User.roles
    when "Admin"
      User.roles
    when "AccountManager"
      User.roles.select{ |x| x == "Company" }

    when "Verification Officer"
      User.roles.select{ |x| x == "Verification Officer" }
    when "Approving Officer"
      User.roles.select{ |x| x == "Approving Officer" }
    when "Company"
      []
    end
  end

  def self.roles
    ["Admin", "SystemAdmin","AccountManager", "Verification Officer", "Approving Officer", "Company", "Readonly Admin", "Printonly Admin"]
  end
end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout "login"

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy, :update]

  def index
    respond_to do |format|
      format.html
      format.json { render json: UserDatatable.new(params, user: current_user) }
    end
    authorize! :manage, :users
  end


  def show
    authorize! :manage, :users
    unless current_user.my_managable_users.include? @user
      redirect_to root_path and return
    end
  end

  def new
    @user = User.new

  end

  def edit
  end


  def create

    @user = User.new(user_params)
    @user.townships  = params[:user][:townships].reject{ |x| x.blank? }.map{ |x| Township.find_by_ts_pcode(x) }
    respond_to do |format|
      if @user.save
        format.html { redirect_to  get_user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def update

    authorize! :manage, :users
    unless current_user.my_managable_users.include? @user
      redirect_to root_path and return
    end
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    respond_to do |format|
      @user.townships  = params[:user][:townships].reject{ |x| x.blank? }.map{ |x| Township.find_by_ts_pcode(x) }
      @user.save
      if @user.update(user_params)
        format.html { redirect_to get_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy

    authorize! :manage, :users
    unless current_user.my_managable_users.include? @user
      redirect_to root_path and return
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email,:ts_pcode, :password, :password_confirmation, :name, :title, :organization_name, :user_role, :work_place_id, :created_by)
    end
end

app/views/users/_form.html.erb
<%= simple_form_for(@user,url: @url) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-group">
	<%= f.input :name, input_html: { class: "form-control"} %>
    </div>

    <div class="form-group">
	<%= f.input :organization_name,  input_html: { class: "form-control"} %>
    </div>

    <div class="form-group">
	<%= f.input :email, input_html: { class: "form-control"} %>
    </div>

    <div class="form-group">
	<%= f.input :password, input_html: { class: "form-control", type: "password"} %>
    </div>



    <div class="form-group">
	<%= f.input :password_confirmation, input_html: { class: "form-control", type: "password"} %>
    </div>

    <% if current_user.my_creatable_roles.count != 0%>
	<div class="form-group">
	    <%= f.input :townships,collection: Township.all.pluck(:name,:ts_pcode),  input_html: { class: "form-control", multiple: true } %>
	</div>
    <% end %>


    <div class="form-group">
	<%= f.input :title,  input_html: { class: "form-control"} %>
    </div>


    <script>
     $("#user_townships").select2();
     $('#user_townships').val(<%= raw(f.object&.townships&.pluck(:ts_pcode)&.map(&:to_s))%>);
     $('#user_townships').trigger("change");

    </script>
    <div class="form-group">
	<%= f.input :user_role,collection: current_user.my_creatable_roles, selected: f.object.user_role %>
    </div>

    <div class="actions">
	<%= f.submit "Save", class: "btn btn-success" %>
    </div>
<% end %>
<style>
 .select2-container .select2-selection--multiple .select2-selection__choice{
     color: black;
 }
</style>

app/views/users/edit.html.erb
<h3>Edit User</h3>
<% @url = update_user_path(id: @user.id)  %>
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, class: "btn btn-light mb-3" %>

app/views/users/index.html.erb
<% if notice.present? %>
    <div class="alert alert-success" role="alert">
	<strong>Success - </strong> <%= notice %>
    </div>
<% end %>
<h3 class="mt-2"><%= t("users") %></h3>



<%= link_to t(:new, name: t("user")), new_user_path, class: "btn btn-outline-info", type: "button" %>

<%= render(DataTableComponent.new(keys: User.view_columns.keys,url: users_path)) %>

app/views/users/new.html.erb
<h3><%= t("new", name: t("user")) %></h3>
<% @url = create_user_path  %>
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, class: "btn btn-light mb-3" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h3> <%= t("user_details") %> </h3>
<div class="row">
    <div class="col-6">
	<div class="card">
	    <div class="card-body">
		<div class="dropdown float-right">
                    <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
			<i class="dripicons-dots-3"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
			<!-- item-->
			<a href="" class="dropdown-item">
			    <i class="mdi mdi-key-link  mr-1"></i><%= t("reset_password") %>
			</a>
			<a href="<%=  edit_user_path(@user)%>" class="dropdown-item"><i class="mdi mdi-pencil mr-1"></i>Edit</a>

			<!-- item-->
			<a href="<%= destroy_user_path(@user, method: :delete) %>" class="dropdown-item"><i class="mdi mdi-delete mr-1"></i>Delete</a>
			<!-- item-->

                    </div>
		</div>
		<!-- project title-->
		<h3 class="mt-0">
		    <%= @user.name %>
		</h3>
		<div class="badge badge-primary mb-3"> <%=  @user.email %></div>
		<div class="badge badge-danger mb-3"> <%=  @user.user_role %></div>


		<h5><%= @user.organization_name %>:</h5>
		<p class="text-muted mb-2">
		    <%= @user.title  %>
		</p>

		<p class="text-muted mb-2">
		    <% if @user.workplaces.exists? %>
			<%= link_to @user.workplaces.first.name,workplace_path(@user.workplaces.first) %>
		    <% end %>
		</p>

	    </div>

        </div>
    </div>
</div>

<%= link_to 'Back', workplaces_path %>