config/routes.rb
Rails.application.routes.draw do
  get 'summary/index'
  get 'registered_business/index'
  resources :extra_employees
  resources :townships
  devise_for :users, controllers: {
    sessions: 'users/sessions'
             }


  resources :application_requests
  resources :workplaces
  get 'home/index'
  get 'users', to: "users#index"
  get 'users/new' => "users#new", as: :new_user



  get 'user/:id' => "users#show", as: :get_user
  post 'create_user' => "users#create", as: :create_user
  patch 'update_user/:id' => "users#update", as: :update_user
  get 'edit_user/:id' => "users#edit", as: :edit_user
  delete "destroy_user/:id" => "users#destroy", as: :destroy_user

  get "my_application_requests/:id/new_employees" => "application_requests#new_employees", as: :new_employees
  post "grid_data/batch_create_application_requests/:id", to: "application_requests#batch_create", as: "application_request_batch_create"

  get "my_application_requests/:id/grid" => "application_requests#employee_list", as: :employee_list
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post "grid_data/application_requests/:id", to: "application_requests#data_update", as: "application_requests_data_update"
  delete "grid_data/batch_delete_application_requests/:id", to: "application_requests#batch_delete", as: "application_request_batch_delete"

  post "change_state_application_request/:id", to: "application_requests#change_state", as: "application_request_change_state"
  post "change_state_workplace/:id", to: "workplaces#change_state", as: "workplace_change_state"
  get "public/new_form" => "public_workplaces#new", as: :new_public_form
  post "public/create_form" => "public_workplaces#create", as: :create_public_form
  get "public/success" => "public_workplaces#success", as: :success_form
  root "public_workplaces#index"



  get 'workplaces' => "workplaces#index", aasm_state: "pending", as: "workplaces_index"
  get 'summary/index'
  post 'summary/print'

  post "print_application_request" => "application_requests#print"

end

app/models/workplace.rb
# coding: utf-8
class Workplace < ApplicationRecord
  include Rails.application.routes.url_helpers
  include ActionView::Helpers::UrlHelper
  include AASM
  has_many :user_workplaces,dependent: :destroy
  has_many :users, through: :user_workplaces,dependent: :destroy
  belongs_to :township,:foreign_key => "ts_pcode", :primary_key => "ts_pcode"


  belongs_to :owner,class_name: "User", primary_key: "id", foreign_key: "owner_id",dependent: :destroy
  validates_presence_of :owner
  validates_presence_of :name
  validates_presence_of :address
  validates_presence_of :township




  has_many :application_requests, dependent: :destroy

  accepts_nested_attributes_for :owner,  reject_if: proc { |attributes| attributes['email'].blank? }

  aasm do
    state :pending, initial: true
    state :accepted
    state :rejected

    event :accept do
      transitions from: :pending, to: :accepted

    end

    event :reject do

      transitions from: :pending, to: :rejected
    end
  end


  def create_application_request
    if application_requests.where.not(aasm_state: "rejected").count != request_limit
      if accepted?
        ApplicationRequest.create(workplace: self,
                                  organization_name: self.name,
                                  address: self.address,
                                  owner_name: owner.name,
                                  ts_pcode: ts_pcode)
      end
    else
      application_requests.first
    end
  end

  def self.view_columns
    {
      id: { source: "Workplace.id",cond: :eq },
      name: { source: "Workplace.name",cond: :like },
      address: { source: "Workplace.address",cond: :like },
      owner: { source: "User.name", cond: :eq },
      owner_email: { source: "User.email", cond: :eq },
      township: { source: "Township.name", cond: :eq},
      actions: { source: "Workplace.id" }
      # id: { source: "User.id", cond: :eq },
      # name: { source: "User.name", cond: :like }
    }
  end

  def custom_attributes
    actions = ""
    actions += link_to(I18n.t("view"),workplace_path(self),class: "btn btn-link float-left")
#    actions += link_to(I18n.t("edit"),edit_workplace_path(self),class: "btn btn-link float-left")
 #   actions += link_to(I18n.t("delete"),workplace_path(self),method: :delete, class: "btn btn-link float-left")



    { township: township&.name, owner: owner&.name, owner_email: owner&.email,actions: actions.html_safe}
  end

end

app/controllers/workplaces_controller.rb
class WorkplacesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_workplace, only: [:show, :edit, :update, :destroy, :change_state]

  # GET /workplaces
  # GET /workplaces.json
  def index

    respond_to do |format|
      format.html
      format.json { render json: WorkplaceDatatable.new(params, user: current_user, aasm_state: params[:aasm_state]) }
    end
    authorize! :manage, :workplaces
  end

  # GET /workplaces/1
  # GET /workplaces/1.json
  def show
    @owner = @workplace.owner
    authorize! :read, @workplace
  end

  # GET /workplaces/new
  def new
    @workplace = Workplace.new
    @workplace.owner = User.new
  end

  def change_state
    authorize! :read, @workplace
    unless params[:state] == "reset"
      @workplace.send("#{params[:state].to_s}!")
    else
      @workplace.owner.send_reset_password_instructions
    end
    if params[:state] == "accept"
      @workplace.owner.send_reset_password_instructions
    end
    redirect_to @workplace
  end



  # GET /workplaces/1/edit
  def edit


  end

  # POST /workplaces
  # POST /workplaces.json
  def create

    @workplace = Workplace.new(workplace_params)

    @workplace.created_by = current_user.id
    respond_to do |format|
      if @workplace.save
        @workplace.accept!
        format.html { redirect_to @workplace, notice: 'Workplace was successfully created.' }

        format.json { render :show, status: :created, location: @workplace }
      else
        format.html { render :new }
        format.json { render json: @workplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workplaces/1
  # PATCH/PUT /workplaces/1.json
  def update
    if params[:owner_attributes][:password].blank? && params[:owner_attributes][:password_confirmation].blank?
      params[:owner_attributes].delete(:password)
      params[:owner_attributes].delete(:password_confirmation)
    end
    authorize! :update, @workplace
    respond_to do |format|
      if @workplace.update(workplace_params)
        @workplace.update(created_by: current_user.id)
        format.html { redirect_to @workplace, notice: 'Workplace was successfully updated.' }
        format.json { render :show, status: :ok, location: @workplace }
      else
        format.html { render :edit }
        format.json { render json: @workplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workplaces/1
  # DELETE /workplaces/1.json
  def destroy
    authorize! :destroy, @workplace
    @workplace.destroy
    respond_to do |format|
      format.html { redirect_to workplaces_url, notice: 'Workplace was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workplace
      @workplace = Workplace.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workplace_params
      params.require(:workplace).permit(:name, :address,:ts_pcode, :request_limit, :created_by,owner_attributes: [:name,:email,:password,:password_confirmation, :organization_name, :title,:user_role])
    end
end

app/helpers/workplaces_helper.rb
module WorkplacesHelper
end

app/views/workplaces/_form.html.erb
<%= simple_form_for(@workplace) do |f| %>
    <div class="card">

	<div class="card-body">
	    <%= f.error_notification %>
	    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
	    <ul>
	    <% f.object.errors.full_messages.each do |error_message| %>
		<li><span class="text-danger"><%= error_message %></span> </li>
	    <% end %>
	    </ul>
	    <div class="form-group">
		<%= f.input :ts_pcode,collection: current_user.townships.pluck(:name, :ts_pcode), label: 'Township', selected: f.object.ts_pcode, input_html: { class: "form-control"} %>
	    </div>

	    <div class="form-group">
		<%= f.input :name,  input_html: { class: "form-control"} %>
	    </div>

	    <div class="form-group">
		<%= f.input :address, input_html: { class: "form-control"} %>
	    </div>


	</div>
    </div>
    <h3 class="mb-3"><%= t("owner") %>  </h3>
    <div class="card">

	<div class="card-body">
	    <%= f.simple_fields_for :owner do |f| %>
		<%= f.error_notification %>
		<% if f.object.present? %>
		    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
		<% end %>
		<div class="form-group">
		    <%= f.input :name, input_html: { class: "form-control"} %>
		</div>


		<div class="form-group">
		    <%= f.input :title, input_html: { class: "form-control"} %>
		</div>


		<div class="form-group">
		    <%= f.input :email,  input_html: { class: "form-control"} %>
		</div>

		<div class="form-group">
		    <%= f.input :password, input_html: { class: "form-control", type: "password"} %>
		</div>



		<div class="form-group">
		    <%= f.input :password_confirmation, input_html: { class: "form-control", type: "password"} %>
		</div>





		<%= f.hidden_field :user_role, value: "Company" %>




	    <% end %>

	</div>
    </div>
    <div class="actions">
	<%= f.submit "Save", class: "btn btn-success" %>
    </div>
<% end %>

app/views/workplaces/edit.html.erb
<h3>Editing Workplace</h3>

<%= render 'form', workplace: @workplace %>

<%= link_to 'Show', @workplace %> |
<%= link_to 'Back', workplaces_path %>

app/views/workplaces/index.html.erb
<% if notice.present? %>
    <div class="alert alert-success" role="alert">
	<strong>Success - </strong> <%= notice %>
    </div>
<% end %>

<% if current_user.company? %>
    <h3 class="mt-2"><%= t("my", name: t("workplaces")) %></h3>
<% else %>
    <h3 class="mt-2"><%= t("workplaces") %></h3>
<% end %>


<% if can? :create, :workplaces%>
    <% if current_user.account_manager? or current_user.verification_officer? %>
	<%= link_to t("new",name: t("workplace")), new_workplace_path, class: "btn btn-outline-info", type: "button" %>
    <% end %>
<% end %>

<% if current_user.company? %>
    <% if current_user.workplaces.present? %>
	<div class="col-3 mt-3">
	    <div class="card">
		<div class="row no-gutters align-items-center">

		    <div class="col-md-12">
			<div class="card-body">
			    <h2 class="card-title"><%= current_user.workplaces.first.name %></h2>
			    <p class="card-text">
				<%= current_user.workplaces.first.address%>

			    </p>
			    <p class="card-text"><small class="text-muted">Created at <%= time_ago_in_words( current_user.workplaces.first.created_at)  %> ago</small></p>
			</div> <!-- end card-body-->
		    </div> <!-- end col -->
		</div> <!-- end row-->
	    </div>
	</div>
    <% end %>
<% else %>
    <%= render(DataTableComponent.new(keys: Workplace.view_columns.keys,url: workplaces_path(aasm_state: params[:aasm_state]))) %>
<% end %>

app/views/workplaces/new.html.erb
<h3 class="mb-3"><%= t("new",name: t("workplace")) %></h3>

<%= render 'form', workplace: @workplace %>

<%= link_to 'Back', workplaces_path, class: "btn btn-light" %>

app/views/workplaces/show.html.erb
<p id="notice"><%= notice %></p>
<% if @workplace.accepted? %>
    <%= link_to t(:reset_password), workplace_change_state_path(@workplace, state: "reset"), method: :post, class: "btn btn-success" %>
<% end %>
<% if @workplace.rejected? %>
    <%= link_to t(:delete), workplace_path(@workplace),method: :delete, class: "btn btn-danger" ,data: { confirm: "Are you sure" } %>
<% end %>
<% if @workplace.pending? %>
    <% if current_user.account_manager? %>
	<%= link_to t(:accept), workplace_change_state_path(@workplace, state: "accept"), method: :post, class: "btn btn-success" %>
	<%= link_to t(:reject), workplace_change_state_path(@workplace, state: "reject"), method: :post, class: "mr-3 btn btn-danger" %>
    <% end %>
<% end %>
<h3> <%= t("workplace_details") %> </h3>

<span class="badge badge-primary mb-3 p-2 rounded" style="font-size: 1em"><%= t(@workplace.aasm_state) %></span>
<div class="row">
    <div class="col-6">
	<div class="card">


	    <div class="card-body">

		<!-- project title-->
		<h3 class="mt-0">
		    <%= @workplace.name %>
		</h3>
		<div class="badge badge-primary mb-3">Created at <%= time_ago_in_words(@workplace.created_at) %> ago</div>

		<p class="text-muted mb-2">

                    <%= @workplace.address %>
		</p>
		<h5>Owner:</h5>

		<p class="text-muted mb-2">
		    <%= link_to @workplace.owner.name,get_user_path(@workplace.owner) %>
		</p>

	    </div>

        </div>
    </div>
</div>
<h3> <%= t("owner") %> </h3>
<div class="row mt-3">
    <div class="col-6">
	<div class="card">
	    <div class="card-body">

		<!-- project title-->
		<h3 class="mt-0">
		    <%= @owner.name %>
		</h3>


		<p class="text-muted mb-2">

                    <%= @owner.title %>
		</p>
		<p class="text-muted mb-2">

                    <%= @owner.phone_number %>
		</p>


		<p class="text-muted mb-2">

                    <%= @owner.email %>
		</p>

	    </div>

        </div>
    </div>
</div>

<%= link_to 'Back', workplaces_path %>