config/routes.rb
Rails.application.routes.draw do
  get 'summary/index'
  get 'registered_business/index'
  resources :extra_employees
  resources :townships
  devise_for :users, controllers: {
    sessions: 'users/sessions'
             }


  resources :application_requests
  resources :workplaces
  get 'home/index'
  get 'users', to: "users#index"
  get 'users/new' => "users#new", as: :new_user



  get 'user/:id' => "users#show", as: :get_user
  post 'create_user' => "users#create", as: :create_user
  patch 'update_user/:id' => "users#update", as: :update_user
  get 'edit_user/:id' => "users#edit", as: :edit_user
  delete "destroy_user/:id" => "users#destroy", as: :destroy_user

  get "my_application_requests/:id/new_employees" => "application_requests#new_employees", as: :new_employees
  post "grid_data/batch_create_application_requests/:id", to: "application_requests#batch_create", as: "application_request_batch_create"

  get "my_application_requests/:id/grid" => "application_requests#employee_list", as: :employee_list
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post "grid_data/application_requests/:id", to: "application_requests#data_update", as: "application_requests_data_update"
  delete "grid_data/batch_delete_application_requests/:id", to: "application_requests#batch_delete", as: "application_request_batch_delete"

  post "change_state_application_request/:id", to: "application_requests#change_state", as: "application_request_change_state"
  post "change_state_workplace/:id", to: "workplaces#change_state", as: "workplace_change_state"
  get "public/new_form" => "public_workplaces#new", as: :new_public_form
  post "public/create_form" => "public_workplaces#create", as: :create_public_form
  get "public/success" => "public_workplaces#success", as: :success_form
  root "public_workplaces#index"



  get 'workplaces' => "workplaces#index", aasm_state: "pending", as: "workplaces_index"
  get 'summary/index'
  post 'summary/print'

  post "print_application_request" => "application_requests#print"

end

app/models/extra_employee.rb
class ExtraEmployee < ApplicationRecord
end

app/controllers/extra_employees_controller.rb
class ExtraEmployeesController < ApplicationController
  before_action :set_extra_employee, only: [:show, :edit, :update, :destroy]

  # GET /extra_employees
  # GET /extra_employees.json
  def index
    @extra_employees = ExtraEmployee.all
  end

  # GET /extra_employees/1
  # GET /extra_employees/1.json
  def show
  end

  # GET /extra_employees/new
  def new
    @extra_employee = ExtraEmployee.new
  end

  # GET /extra_employees/1/edit
  def edit
  end

  # POST /extra_employees
  # POST /extra_employees.json
  def create
    @extra_employee = ExtraEmployee.new(extra_employee_params)

    respond_to do |format|
      if @extra_employee.save
        format.html { redirect_to @extra_employee, notice: 'Extra employee was successfully created.' }
        format.json { render :show, status: :created, location: @extra_employee }
      else
        format.html { render :new }
        format.json { render json: @extra_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extra_employees/1
  # PATCH/PUT /extra_employees/1.json
  def update
    respond_to do |format|
      if @extra_employee.update(extra_employee_params)
        format.html { redirect_to @extra_employee, notice: 'Extra employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @extra_employee }
      else
        format.html { render :edit }
        format.json { render json: @extra_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extra_employees/1
  # DELETE /extra_employees/1.json
  def destroy
    @extra_employee.destroy
    respond_to do |format|
      format.html { redirect_to extra_employees_url, notice: 'Extra employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extra_employee
      @extra_employee = ExtraEmployee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def extra_employee_params
      params.require(:extra_employee).permit(:ward, :street, :house_no, :name, :gender, :nric, :date_of_birth, :job, :workplace)
    end
end

app/helpers/extra_employees_helper.rb
module ExtraEmployeesHelper
end

app/views/extra_employees/_form.html.erb
<%= simple_form_for(@extra_employee) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :ward %>
    <%= f.input :street %>
    <%= f.input :house_no %>
    <%= f.input :name %>
    <%= f.input :gender %>
    <%= f.input :nric %>
    <%= f.input :date_of_birth %>
    <%= f.input :job %>
    <%= f.input :workplace %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/extra_employees/edit.html.erb
<h1>Editing Extra Employee</h1>

<%= render 'form', extra_employee: @extra_employee %>

<%= link_to 'Show', @extra_employee %> |
<%= link_to 'Back', extra_employees_path %>

app/views/extra_employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Extra Employees</h1>

<table>
  <thead>
    <tr>
      <th>Ward</th>
      <th>Street</th>
      <th>House no</th>
      <th>Name</th>
      <th>Gender</th>
      <th>Nric</th>
      <th>Date of birth</th>
      <th>Job</th>
      <th>Workplace</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @extra_employees.each do |extra_employee| %>
      <tr>
        <td><%= extra_employee.ward %></td>
        <td><%= extra_employee.street %></td>
        <td><%= extra_employee.house_no %></td>
        <td><%= extra_employee.name %></td>
        <td><%= extra_employee.gender %></td>
        <td><%= extra_employee.nric %></td>
        <td><%= extra_employee.date_of_birth %></td>
        <td><%= extra_employee.job %></td>
        <td><%= extra_employee.workplace %></td>
        <td><%= link_to 'Show', extra_employee %></td>
        <td><%= link_to 'Edit', edit_extra_employee_path(extra_employee) %></td>
        <td><%= link_to 'Destroy', extra_employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Extra Employee', new_extra_employee_path %>

app/views/extra_employees/new.html.erb
<h1>New Extra Employee</h1>

<%= render 'form', extra_employee: @extra_employee %>

<%= link_to 'Back', extra_employees_path %>

app/views/extra_employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ward:</strong>
  <%= @extra_employee.ward %>
</p>

<p>
  <strong>Street:</strong>
  <%= @extra_employee.street %>
</p>

<p>
  <strong>House no:</strong>
  <%= @extra_employee.house_no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @extra_employee.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @extra_employee.gender %>
</p>

<p>
  <strong>Nric:</strong>
  <%= @extra_employee.nric %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @extra_employee.date_of_birth %>
</p>

<p>
  <strong>Job:</strong>
  <%= @extra_employee.job %>
</p>

<p>
  <strong>Workplace:</strong>
  <%= @extra_employee.workplace %>
</p>

<%= link_to 'Edit', edit_extra_employee_path(@extra_employee) %> |
<%= link_to 'Back', extra_employees_path %>