config/routes.rb
Rails.application.routes.draw do
  get 'summary/index'
  get 'registered_business/index'
  resources :extra_employees
  resources :townships
  devise_for :users, controllers: {
    sessions: 'users/sessions'
             }


  resources :application_requests
  resources :workplaces
  get 'home/index'
  get 'users', to: "users#index"
  get 'users/new' => "users#new", as: :new_user



  get 'user/:id' => "users#show", as: :get_user
  post 'create_user' => "users#create", as: :create_user
  patch 'update_user/:id' => "users#update", as: :update_user
  get 'edit_user/:id' => "users#edit", as: :edit_user
  delete "destroy_user/:id" => "users#destroy", as: :destroy_user

  get "my_application_requests/:id/new_employees" => "application_requests#new_employees", as: :new_employees
  post "grid_data/batch_create_application_requests/:id", to: "application_requests#batch_create", as: "application_request_batch_create"

  get "my_application_requests/:id/grid" => "application_requests#employee_list", as: :employee_list
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post "grid_data/application_requests/:id", to: "application_requests#data_update", as: "application_requests_data_update"
  delete "grid_data/batch_delete_application_requests/:id", to: "application_requests#batch_delete", as: "application_request_batch_delete"

  post "change_state_application_request/:id", to: "application_requests#change_state", as: "application_request_change_state"
  post "change_state_workplace/:id", to: "workplaces#change_state", as: "workplace_change_state"
  get "public/new_form" => "public_workplaces#new", as: :new_public_form
  post "public/create_form" => "public_workplaces#create", as: :create_public_form
  get "public/success" => "public_workplaces#success", as: :success_form
  root "public_workplaces#index"



  get 'workplaces' => "workplaces#index", aasm_state: "pending", as: "workplaces_index"
  get 'summary/index'
  post 'summary/print'

  post "print_application_request" => "application_requests#print"

end

app/models/application_request.rb
class ApplicationRequest < ApplicationRecord
  include Rails.application.routes.url_helpers
  include ActionView::Helpers::UrlHelper
  belongs_to :workplace
  has_many :employees, dependent: :destroy
  has_one_attached :attachment
  include AASM

  belongs_to :verify_by,class_name: "User", primary_key: "id", foreign_key: "verify_by",optional: true
  belongs_to :reject_by,class_name: "User", primary_key: "id", foreign_key: "reject_by",optional: true
  belongs_to :approve_by,class_name: "User", primary_key: "id", foreign_key: "approve_by", optional: true
  belongs_to :submit_by,class_name: "User", primary_key: "id", foreign_key: "submit_by", optional: true

#  validates :attachment,  blob: { content_type: :image } # supported options: :image, :audio, :video, :text
  aasm do
    state :draft, initial: true
    state :submitted
    state :rejected
    state :verified, :approved

    event :submit do
      transitions from: :draft, to: :submitted
    end

    event :verify do
      transitions from: :submitted, to: :verified
    end

    event :reject do
      transitions from: :submitted, to: :rejected
      transitions from: :verified, to: :rejected
      transitions from: :approved, to: :rejected
    end

    event :approve do
      transitions from: :verified, to: :approved
    end


  end

  def missing_columns
    my_missing_columns = []
    columns = [:organization_registration_no, :owner_phone,  :employer_ssn]
    columns.each do |item|

      if self.instance_eval(item.to_s).blank?
        my_missing_columns << item
      end
    end

    if !attachment.attached?
      my_missing_columns << :attachment
    end
    my_missing_columns
  end

  def self.view_columns
    {
      id: { source: "ApplicationRequest.id", cond: :eq},
      workplace: { source: "Workplace.name", cond: :like},
      state: { source: "ApplicationRequest.aasm_state", cond: :like},
      submitted_at: { source: "ApplicationRequest.created_at", cond: :like},
      verify_by: { source: "ApplicationRequest.id", cond: :like},
      approve_by: { source: "ApplicationRequest.id", cond: :like},
      last_action_at: { source: "Workplace.updated_at", cond: :like},
      actions: { source: "ApplicationRequest.id", cond: :eq }
    }
  end

  def custom_attributes
    actions = ""
    if aasm_state == "draft"
      actions += button_to(I18n.t("print"), print_application_request_path(),params: { id: self.to_sgid.to_s}, class: "btn btn-link float-left", method: :post, form:{ target: "_blank" })
      actions += link_to(I18n.t("edit"),edit_application_request_path(self),class: "btn btn-link float-left")
    end
    actions += link_to(I18n.t("view"),application_request_path(self),class: "btn btn-link float-left")
    {
      workplace: workplace.name ,
      state: aasm_state.humanize,
      verify_by: verify_by&.name,
      approve_by: approve_by&.name,
      submitted_at: created_at.strftime("%Y-%m-%d"),
      last_action_at: updated_at.strftime("%Y-%m-%d"),
       actions: actions.html_safe
    }
  end
end

app/controllers/application_requests_controller.rb
class ApplicationRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_application_request, only: [:show, :edit, :update, :destroy, :new_employees, :batch_create, :employee_list, :batch_delete, :change_state]
  skip_before_action :verify_authenticity_token
  layout "application_request_print", :only => [ :print ]

  # GET /application_requests
  # GET /application_requests.json
  def index
    current_user.generate_application_requests

    respond_to do |format|
      format.html
      format.json { render json: ApplicationRequestDatatable.new(params, user: current_user) }
    end
  end

  def change_state
    if current_user.readonly_admin?
      redirect_to root_path
    end
    if params[:state].to_s == "submit"
      if @application_request.employees.count == 0
        redirect_to @application_request, notice: 'Please fill the employees' and return

      end
      if @application_request.missing_columns.count > 0
        redirect_to @application_request, notice: 'Please fill the remaining fields' and return
      end

      if !@application_request.attachment.attached?
        redirect_to @application_request, notice: 'Please attach the attachment' and return
      end
    end


    @application_request.update("#{params[:state].to_s}_at": Date.today)
    @application_request.update("#{params[:state].to_s}_by": current_user)
    @application_request.send("#{params[:state].to_s}!")
    redirect_to @application_request
  end

  def employee_list
    render partial: "employee_list", locals: { employees_json: @employees_json }
  end

  def new_employees
    unless current_user.company?
      redirect_to root_path
    end
  end

  def batch_delete
    payload = JSON.parse(params["payload"])
    payload.each do |item|
      employee= Employee.find_by_id(item["id"])
      if current_user.my_managable_application_requests.include? employee.application_request
        update_data = employee.destroy
      end

    end
  end

  def batch_create
    unless current_user.company?
      redirect_to root_path
    end
    if current_user.readonly_admin?
      redirect_to root_path
    end
    rows = params["rows"]
    items = rows.each do |item|
      item = Employee.new(item.permit!.except("school", "inventory_item_category", "id"))
      item.application_request = @application_request
      item.save
    end
    redirect_to @application_request
  end

  # GET /application_requests/1
  # GET /application_requests/1.json
  def show
    if current_user.my_managable_application_requests.include? @application_request
      @employees_json  = (@application_request.employees.map do |item| EmployeeSerializer.new(item, params: params).to_hash end).to_json
      puts @employees_json
    else
      redirect_to root_path
    end
  end


  def data_update

    payload = JSON.parse(params["payload"])
    employee= Employee.find_by_id(params["id"])
    if current_user.my_managable_application_requests.include? employee.application_request
      update_data = employee.update(payload)
    end
    employee.reload
    render json: employee
  end

  # GET /application_requests/new
  def new
    @application_request = ApplicationRequest.new
  end

  # GET /application_requests/1/edit
  def edit
    unless current_user.my_managable_application_requests.include? @application_request
      if current_user.readonly_admin?
        redirect_to root_path
      end
    end
  end

  def print
  end

  # POST /application_requests
  # POST /application_requests.json
  def create
    @application_request = ApplicationRequest.new(application_request_params)
    if @application_request.status == "VERIFIED"
      @application_request.verified_at = DateTime.now
      @application_request.rejected_at = nil
      @application_request.approved_at = nil
      @application_request.verified_by = current_user.id
      @application_request.approved_by = nil
    elsif @application_request.status == "REJECTED"
      @application_request.rejected_at = DateTime.now
      @application_request.verified_at = nil
      @application_request.approved_at = nil
      @application_request.verified_by = nil
      @application_request.approved_by = nil
    elsif @application_request.status == "APPROVED"
      @application_request.approved_at = DateTime.now
      @application_request.verified_at = nil
      @application_request.rejected_at = nil
      @application_request.approved_by = current_user.id
      @application_request. verified_by = nil
    else
      @application_request.approved_at = nil
      @application_request.verified_at = nil
      @application_request.rejected_at = nil
      @application_request.verified_by = nil
      @application_request.approved_by = nil
    end
    respond_to do |format|
      if @application_request.save
        format.html { redirect_to @application_request, notice: 'Application request was successfully created.' }
        format.json { render :show, status: :created, location: @application_request }
      else
        format.html { render :new }
        format.json { render json: @application_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /application_requests/1
  # PATCH/PUT /application_requests/1.json
  def update
    respond_to do |format|
      if @application_request.update(application_request_params)
        format.html { redirect_to @application_request, notice: 'Application request was successfully updated.' }
        format.json { render :show, status: :ok, location: @application_request }
      else
        format.html { render :edit }
        format.json { render json: @application_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_requests/1
  # DELETE /application_requests/1.json
  def destroy
    @application_request.destroy
    respond_to do |format|
      format.html { redirect_to application_requests_url, notice: 'Application request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def print
    id = GlobalID::Locator.locate_signed(params[:id]).id
    @application_requests = ApplicationRequest.where(id: id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application_request
      @application_request = ApplicationRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def application_request_params
      params.require(:application_request).permit(:work_place_id, :status, :verified_at, :rejected_at, :approved_at, :verified_by, :approved_by, :employee_list, :organization_name, :organization_registration_no, :ts_pcode, :phone, :employer_ssn, :is_running,:address, :owner_name, :owner_phone,:attachment, :remark)
    end
end

app/helpers/application_requests_helper.rb
module ApplicationRequestsHelper
end

app/views/application_requests/_employee_list.html.erb
<div class="row">
    <div class="col-12"
	 data-controller="employee-grid"
	 data-employee-grid-editable="true"
    	 data-employee-grid-url="">
	<div id="myGrid"
	     style="height: 600px;width:100%;"
	     class="ag-theme-alpine mt-3"
	     data-action="updateGrid@window->employee#update"
	     data-target="employee-grid.grid">

	</div>
    </div>
</div>

app/views/application_requests/_file_upload_modal.html.erb
<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-controller="upload-excel">
    <div class="modal-dialog" role="document">
	<div class="modal-content">
	    <div class="modal-header">
		<h5 class="modal-title" id="exampleModalLabel">Upload Excel</h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		    <span aria-hidden="true">&times;</span>
		</button>
	    </div>

	    <div class="modal-body">
		<input type="file" id="fileUpload" class="form-control" data-target="upload-excel.file" />

	    </div>
	    <div class="modal-footer">
		<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		<input type="button"
		       id="upload"
		       value="Upload"
		       data-action="click->upload-excel#upload"

		       class="btn btn-primary"
		       data-dismiss="modal"/>
	    </div>
	</div>
    </div>
</div>

app/views/application_requests/_form.html.erb
<%= simple_form_for(@application_request,:method => :patch,url: application_request_path(@application_request)) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :organization_name %>
    <%= f.input :organization_registration_no %>
    <%= f.input :owner_name %>
    <%= f.input :owner_phone %>
    <%= f.input :is_running %>
    <%= f.input :address %>
    <%= f.input :employer_ssn %>
    <%= f.input :attachment, input_html: { accept: "image/*" } %>
    <%= f.input :ts_pcode,collection: Township.all.pluck(:name, :ts_pcode), selected: f.object.ts_pcode, input_html: { class: "form-control"} %>




    <div class="actions">
	<%= f.submit "Save", class: "btn btn-success" %>
    </div>
<% end %>

app/views/application_requests/edit.html.erb
<h3>Editing Application Request</h3>

<%= render 'form', application_request: @application_request %>

<%#= link_to 'Show', @application_request %>
<%#= link_to 'Back', application_requests_path %>
<%= link_to 'Back', application_requests_path, class: "btn btn-light" %>

app/views/application_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h3><%= t("application_requests") %></h3>

<% if false == true %>
    <%= link_to 'New Application Request', new_application_request_path, class: "btn btn-outline-info", type: "button" %>
<% end %>

<%= render(DataTableComponent.new(keys: ApplicationRequest.view_columns.keys,url: application_requests_path)) %>


<br>
<% if false == true %>
    <div class="alert alert-success" role="alert">
	<strong>Info - </strong> ဤ Feature အား မဖွင့်သေးပါ။
    </div>
    <div id="svgContainer" class="mx-auto" style="width: 500px;"></div>
    <script>
     var svgContainer = document.getElementById('svgContainer');
     var animItem = bodymovin.loadAnimation({
	 wrapper: svgContainer,
	 animType: 'svg',
	 loop: true,
	 path: '/working.json'
     });
    </script>

<% end %>

app/views/application_requests/new.html.erb
<h1>New Application Request</h1>

<%= render 'form', application_request: @application_request %>

<%= link_to 'Back', application_requests_path, class: "btn btn-light" %>

app/views/application_requests/new_employees.html.erb
<div  data-controller="employee-grid"
      data-employee-grid-editable="false"
      data-employee-grid-redirect-url="<%= application_request_path(@application_request) %>"
      data-employee-grid-post-url="<%= application_request_batch_create_path(id: @application_request.id) %>">
    <div class="row" >
	<div class="col-12">
	    <h3 class="float-left"> <%= link_to @application_request.workplace.name, application_request_path(@application_request) %> / <%= t("employees") %> <span id="rowCount"></span> </h3>

	    <button type="button" class="btn btn-success"  id="btnAddNewRow" data-action="click->employee-grid#saveGrid"><%= t("save") %></button>
	    <%= link_to  "Download Template", "/employees-list-template.xlsx", target: :_blank, class: 'btn btn-primary mr-1' %>

	    <button type="button" class="btn btn-outline-primary mr-1"  data-toggle="modal" data-target="#uploadModal">Upload Excel File</button>




	    <button type="button" class="btn btn-outline-danger mr-1"  id="btnAddNewRow" data-action="click->employee-grid#clear"><%= t("clear") %></button>
	    <button type="button" class="btn btn-outline-info mr-1"  id="btnAddNewRow" data-action="click->employee-grid#back"><%= t("back") %></button>
	    <%= render partial: "file_upload_modal" %>
	</div>
    </div>
    <div class="row">

	<div class="col-12">
	    <div id="myGrid"
		 style="height: 600px;width:100%;"
		 class="ag-theme-alpine mt-3"
		 data-action="updateGrid@window->employee-grid#update"
		 data-target="employee-grid.grid">

	    </div>
	</div>
    </div>
</div>




<script>
 // specify the columns
 var columnDefs = [
     // filter not specified, defaultColDef setting is used
     { headerName: "",field: 'actions',width:70,
       cellRenderer: function (params) {
	   return params.value
       }
     },
     { headerName: "Name",field: 'name', editable: true },
     { headerName: "Gender",field: 'gender',editable: true },
     { headerName: "Date of birth",field: 'date_of_birth',editable: true,cellEditor: 'dateEditor',    filter: 'agDateColumnFilter' },
     { headerName: "Nric",field: 'nric',editable: true },
     { headerName: "Position",field: 'position',editable: true },
     { headerName: "Salary",field: 'salary',editable: true },
     { headerName: "Remark",field: 'ssn_employee_no',editable: true }
 ];
 window.colDefs = columnDefs
</script>
<script>

 window.initialRows = [];

</script>

app/views/application_requests/show.html.erb
<% if notice.present? %>
    <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
	</button>
	<strong></strong><%= notice %>
    </div>
<% end %>
<div  data-controller="employee-grid"
      data-employee-grid-editable="true"
      data-employee-grid-url=""
      data-employee-grid-delete-url="<%= application_request_batch_delete_path(id: @application_request.id) %>">

    <div class="card">
	<div class="card-header">
	    <div class="card-title">
		<h3 class="mm"><%= t("application_request") %></h3>
	    </div>


	    <h4><span class="badge badge-primary badge-pill"><%= @application_request.aasm_state.humanize %></span></h4>

	    <p><%= @application_request.aasm_state.humanize %> at ⟶ <%= time_ago_in_words(@application_request.created_at) %> <span style="color: red"> | </span> Last action at ⟶ <%= @application_request.updated_at&.strftime("%Y-%m-%d") %></p>

	    <dl>

		<dt class="text-black"><%= t(:organization_name) %></dt>
		<dd><%= @application_request.organization_name %></dd>

		<dt class="text-black"><%= t(:organization_registration_no) %></dt>
		<dd><%= @application_request.organization_registration_no %></dd>

		<dt class="text-black"><%= t(:owner_name) %></dt>
		<dd><%= @application_request.owner_name %></dd>

		<dt class="text-black"><%= t(:owner_phone) %></dt>
		<dd><%= @application_request.owner_phone %></dd>


		<% if  @application_request.is_running  %>
		    <dt><%= t(:is_running) %></dt>
		<% end %>

	    </dl>


	</div>


	<div class="card-body">
	    <div class="row">
		<div class="col-12">
		    <%= button_to(I18n.t("print"), print_application_request_path(),params: { id: @application_request.to_sgid.to_s}, class: "btn btn-warning float-left mr-1", method: :post, form:{ target: "_blank" }) %>
		    <% if @application_request.attachment.attached? %>
			<a href="<%= url_for(@application_request.attachment) %>" target="_blank" type="button" class="btn float-left btn-info" style="display: flex;">
			    <div id="download-svgContainer" style="margin: -20px; width: 60px;"></div>
			    <span class="ml-2"><b><%= t("download_attachment") %></span></b></a>
		    <% end %>

		    <% if current_user.account_manager? %>
			<% if @application_request.submitted? %>
			    <%=  link_to "အတည်ပြုပါသည်။",application_request_change_state_path(@application_request, state: "verify"), method: :post, class: "btn float-left btn-outline-success ml-2" %>

			<% end %>
			<% unless @application_request.approved? %>
			    <% unless @application_request.rejected? %>
				<% unless  @application_request.draft? %>
				    <%=  link_to "Reject",application_request_change_state_path(@application_request, state: "reject"), method: :post, class: "btn float-left btn-outline-success ml-2" %>
				<% end %>
			    <% end %>

			<% end %>
		    <% elsif current_user.admin?  %>
			<% if @application_request.verified? %>
			    <%=  link_to "သဘောတူပါသည်။",application_request_change_state_path(@application_request, state: "approve"), method: :post, class: "btn float-left btn-outline-success ml-2" %>

			<% end %>
		    <% elsif current_user.company? %>
			<% if @application_request.draft? %>

			    <%  unless @application_request.missing_columns.present? %>
				<%=  link_to "တင်သွင်းပါသည်။",application_request_change_state_path(@application_request, state: "submit"), method: :post, class: "btn float-left btn-outline-success ml-2 ", data: { confirm: "Are you sure?, You can not undo after this" }%>
			    <% else %>
				<%=  link_to "တင်သွင်းပါသည်။",application_request_change_state_path(@application_request, state: "submit"), method: :post, class: "btn float-left btn-outline-success ml-2 disabled ", data: { confirm: "Are you sure?, You can not undo after this" }%>
			    <% end %>
			<% end %>
		    <% else %>

		    <% end %>


		</div>
	    </div>
	</div>
    </div>
    <% if @application_request.missing_columns.present? %>
	<div class="card cta-box bg-warning text-white">
	    <div class="card-body">
		<div class="media align-items-center">
		    <div class="media-body">
			<h4 style="margin-top: -20px">
			    <div class="row">
				<div id="notification-svgContainer" style="width: 80px;"></div>
				<div class="mt-3"><%= t(:pending_edit) %></div>
			    </div>

			</h4>
			<ul style="margin-top: -20px">
			    <% @application_request.missing_columns.each do |item| %>
				<li> <%= t(item) %></li>

			    <% end %>
			</ul>
			<a href="<%= edit_application_request_path(@application_request) %>">
			    <h5 class="m-0 font-weight-normal text-white" ><b><%= t(:edit_now) %></b>
				<i class="mdi mdi-arrow-right-bold-outline"></i></h5>
			</a>
		    </div>

		</div>
	    </div>
	    <!-- end card-body -->
	</div>
    <% end %>
    <hr class="mt-4">
    <div class="row">
	<div class="col-12">
	    <h3 class="float-left"> <%= t("employees") %><span id="rowCount"></span> </h3>

	    <% if current_user.company?  and @application_request.draft? %>
		<%= link_to 'Delete', "", class: "btn btn-outline-danger ml-2", type: "button", data: {
		    action: "click -> employee-grid#deleteRows"
		} %>
		<%= button_tag  "Select All", type: "button", class: "btn btn-outline-primary ml-2", type: "button", data: {
		    action: "click -> employee-grid#selectAll"
		} %>


		<%= link_to 'Import Excel', new_employees_path(@application_request), class: "btn btn-outline-info", type: "button" %>
		<%= link_to  "Download Template", "/employees-list-template.xlsx", target: :_blank, class: 'btn btn-primary mr-1' %>
	    <% end %>

	</div>
    </div>
    <script>
     // specify the columns
     var editable = <%= raw(@application_request.draft?) %>
     var columnDefs = [
	 // filter not specified, defaultColDef setting is used
	 { headerName: "",field: 'actions',width:70, checkboxSelection: editable},
	 { headerName: "Name",field: 'name', editable: editable },
	 { headerName: "Gender",field: 'gender',editable: editable },
	 { headerName: "Date of birth",field: 'date_of_birth',editable: editable,cellEditor: 'dateEditor',    filter: 'agDateColumnFilter' },
	 { headerName: "Nric",field: 'nric',editable: editable },
	 { headerName: "Position",field: 'position',editable: editable },
	 { headerName: "Salary",field: 'salary',editable: editable },
	 { headerName: "Remark",field: 'ssn_employee_no',editable: editable }
     ];
     window.colDefs = columnDefs
    </script>
    <script>



     window.initialRows =  <%= @employees_json.html_safe %>;



    </script>


    <div class="row">
	<div class="col-12"
	>

	    <div id="myGrid"
		 style="height: 600px;width:100%;"
		 class="ag-theme-alpine mt-3"
		 data-action="updateGrid@window->employee#update"
		 data-target="employee-grid.grid">

	    </div>
	</div>
    </div>

</div>

<script data-turbolinks-eval="false">
 var svgContainer = document.getElementById('notification-svgContainer');
 var animItem = bodymovin.loadAnimation({
     wrapper: svgContainer,
     animType: 'svg',
     loop: true,
     path: '/notification.json'
 });

 var downloadSvgContainer = document.getElementById('download-svgContainer');
 bodymovin.loadAnimation({
     wrapper: downloadSvgContainer,
     animType: 'svg',
     loop: true,
     path: '/download.json'
 });
</script>
<style>
 dt{
     color: black;
     font-family: Pyidaungsu,Yunghkio;
 }
 dd{

     font-family: Pyidaungsu,Yunghkio;
 }
</style>